# Template config file.
# Here you can specify the paths to the input and output, specify the experiment design for differential express analysis, and other additional parameters.
# Arguments are specified in a key:value format, do NOT change the key names.

#####################
# Input and output
#####################

# It is recommended to provide absolute paths, i.e. beginning with root (/).
# Else, paths are considered to be relative to the location from which snakemake is called.


# Fastq files containing paired RNA-seq reads, 1 pair per replicate
reads:
  sample_1: #Sample 1. Provide the paired files as a list of 2 items.
    [ /path/to/sample1_L.fastq, /path/to/smaple1_R.fastq ] # Do not remove the [ and ]. Separate the file names by a comma.
  sample_2: #Sample 2.
    [ /path/to/sample2_L.fastq, /path/to/sample2_R.fastq]
  sample_3: #Sample 2.
    [ /path/to/sample3_L.fastq, /path/to/sample3_R.fastq]
#add more samples as needed

# Output folder
out_dir: /path/to/output/folder

# Reference protein database for annotation.
reference_p: /path/to/reference/proteome
