---
title: "R Notebook"
---

```{r}
loadDependencies()
dseq_orig <- importRSEM("data/counts_per_sample")

df_annot.orig <- read.csv(getPath_fromProjWd("data/annotation.20200701.csv"), stringsAsFactors = FALSE)
annotSignif <- 1e-10
alnLenThreshold <- 50

df_annot <- df_annot.orig %>% filter(fly_stat_sig < annotSignif & fly_len_perc >= alnLenThreshold )

keep <- unique(df_annot$gene_id)
```

```{r}
in_dir <- "data/RSEM.gene.TMM.EXPR.matrix"
# in_dir <- "data/RSEM.gene.TPM.not_cross_norm"
method <- "TMM"   # or TPM

out_dir <- "results/PCA Read count methods"
```

```{r}
# install.packages("factoextra")
# install.packages("janitor")
library(factoextra)
library(janitor)
library(dplyr)

counts <- read.csv(getPath_fromProjWd(in_dir), sep="\t")
filtered <- counts[counts$X %in% keep,] 
counts_t <- t(filtered[,-1]) %>% data.frame()

counts_t <- log(counts_t + 1, base=2)

colnames(counts_t) <- filtered[,1]

res_pca <- prcomp(counts_t)
```


```{r}
pcaeig_plotdata <- get_eig(res_pca)
pcacoord_plotdata <- get_pca_ind(res_pca)

pca_plotdata <- pcacoord_plotdata$coord %>% data.frame() %>% 
                select("Dim.1", "Dim.2") %>%  rename("Dim.1" = "PC1") %>% rename("Dim.2" = "PC2") %>% 
                rownames_to_column("samplename") %>% 
                mutate(location = as.factor(substr(samplename, 1, 3))) %>% 
                mutate(condition = as.factor(substr(samplename, 5,5)))
pca_plotdata$location <- relevel(pca_plotdata$location, ref = "CAG")
percentVar <- round(pcaeig_plotdata$variance.percent[1:2],2)

p <- ggplot(pca_plotdata, aes(PC1, PC2)) +
         geom_point(size=2) +
         xlab(paste0("PC1: ",percentVar[1],"% variance")) +
         ylab(paste0("PC2: ",percentVar[2],"% variance")) +
         coord_fixed() +
         ggtitle(label = "PCA of transformed counts", subtitle = paste0("using ", method)) +
         aes(color = location, shape=condition) +
         scale_shape_manual(values=c(1,0)) +
         theme_bw()

p2 <-  p + geom_text_repel(aes(label = samplename),
                  box.padding   = 0.3,
                  point.padding = 0.1,
                  size = 3,
                  segment.color = 'gray88')
print(p)
print(p2)
savePlot(p, 6, 6, filedir = out_dir, filename = method)
savePlot(p2, 6, 6, filedir = out_dir, filename = paste0(method, " (labeled)"))
```

