---
title: "Tracking HSP genes in annotation filter"
---

Notes:
1. HCYE_APHSP (not a HSP gene), so the checking would now be substring of 1st to 3rd char

```{r}
loadDependencies()

dseq_orig <- importRSEM("data/counts_per_sample")
df_geneIDs <- group_by(getDfAnnot(), gene_id) %>% 
  summarise(swiss_prot = paste(swiss_prot, collapse = ", "), fly = paste(fly, collapse = ", "))

# 1. Group by gene Id
# 2. Count number of HSP per gene
# 3. Use this dataframe to keep track the genes with HSP along the DEG workflow

getHSPGenes <- function(filtered = NA, geneids = NA, source){
  if(!is.na(filtered)){
    geneids <- row.names(counts(filtered@dseq))
  }
  df_hsp <- df_geneIDs %>%  
    filter(gene_id %in% geneids) %>% 
    filter(sapply(sapply(strsplit(.[[source]], ", "), function(x) substr(x, 1, 3) == "HSP"), sum) > 0)
    # ^Return True if any of the swiss_prot/fly (whichever specified) has "HSP" in the first three characters   
  
  return(df_hsp)
}

trackHSPGenes <- function(filtered, source="swiss_prot", fitted = NA){  # source=c("swiss_prot","fly")
  if(is.na(fitted)){
    fitted <- modelfit(filtered)
  }
  
  df_hsp <- getHSPGenes(filtered = filtered, source = source)
  
  # Count how many are in outliers
  cooksCutoff <- qf(df1 = 6, df2 = length(fitted@dseq$samplename) - 6, p = .99)
  df_outliers <- mcols(fitted@dseq, use.names = TRUE) %>% 
    data.frame() %>% 
    subset(maxCooks > cooksCutoff) %>% 
    rownames_to_column("gene_id")
  
  df_outliersHsp <- df_hsp %>%  filter(gene_id %in% df_outliers$gene_id)
  
  writeLines(paste0("\nAfter filtering, the number of genes with 'HSP' in ",source," ID is : [ ", nrow(df_hsp), " ]"))
  writeLines(paste0("After fitting, number of outliers are : [ ", nrow(df_outliers), " ]"))
  writeLines(paste0("Number of HSP considered as an outlier : [ ", nrow(df_outliersHsp), " ]"))
  # writeLines(paste0("Number of remaining HSPs left for testing : [ ", nrow(df_hsp) - nrow(df_outliersHsp), " ]"))
  
  # Perform Hypothesis Testing
  for(testId in list("BAT.E","BIC.E","BAT.E-BIC.E", "E", "E+BAT.E", "E+BIC.E")){
    fitted <- signifTest(fitted, testId)
  }
  
  for(resData in fitted@list_plotResData){
    
    # Count how many are removed by independent filtering
    meanCutoff <- metadata(resData@res)$filterThreshold[[1]]

    df_lowMean <- data.frame(resData@res) %>% 
      rownames_to_column("gene_id") %>% 
      subset(!is.na(pvalue)) %>%
      subset(!gene_id %in% df_outliers$gene_id) %>%  # make sure outliers are already filtered out
      subset(baseMean < meanCutoff)
    
    df_lowMeanHsp <- df_hsp %>%  filter(gene_id %in% df_lowMean$gene_id)
  
    # Count how many HSPs are left for testing
    cnt_hspForTesting <- nrow(df_hsp) - nrow(df_outliersHsp) - nrow(df_lowMeanHsp)
    
    # Count how many are DE genes
    list_degenes <- resData@df_degenes$genes
    cnt_HSPdegenes <- sum(list_degenes %in% df_hsp$gene_id)  
    writeLines(paste0("\nIn ", resData@testId))
    writeLines(paste0("        Genes removed by independent filtering : ", nrow(df_lowMean), " (", nrow(df_lowMeanHsp), " HSPs)"))
    writeLines(paste0("        Final number of HSP genes remaining for testing : (", cnt_hspForTesting, " HSPs)"))
    writeLines(paste0("        Number of DE genes : ",length(list_degenes), " (", cnt_HSPdegenes, " HSPs)"))
  }
  beep()
}
```

# Problem 1: Where did the HSP genes went?  
```{r}
# Gene Filter : Annotation from Five databases with Significance 10e-10
# Sample Filter : No BAT_E_2, CAG_C_3, CAG_E_1, BIC_C_3
# 
# After filtering, the number of genes with 'HSP' in swiss_prot ID is : [ 49 ]
# After fitting, number of outliers are : [ 24 ]
# Number of HSP considered as an outlier : [ 1 ]
# 
# In BAT.E
#         Genes removed by independent filtering : 2952 (41 HSPs)
#         Final number of HSP genes remaining for testing : (7 HSPs)
#         Number of DE genes : 503 (0 HSPs)
# 
# In BIC.E
#         Genes removed by independent filtering : 0 (0 HSPs)
#         Final number of HSP genes remaining for testing : (48 HSPs)
#         Number of DE genes : 3 (0 HSPs)
# 
# In BAT.E-BIC.E
#         Genes removed by independent filtering : 2833 (38 HSPs)
#         Final number of HSP genes remaining for testing : (10 HSPs)
#         Number of DE genes : 54 (0 HSPs)
# 
# In E
#         Genes removed by independent filtering : 3660 (42 HSPs)
#         Final number of HSP genes remaining for testing : (6 HSPs)
#         Number of DE genes : 104 (0 HSPs)
# 
# In E+BAT.E
#         Genes removed by independent filtering : 2370 (33 HSPs)
#         Final number of HSP genes remaining for testing : (15 HSPs)
#         Number of DE genes : 946 (2 HSPs)
# 
# In E+BIC.E
#         Genes removed by independent filtering : 2018 (30 HSPs)
#         Final number of HSP genes remaining for testing : (18 HSPs)
#         Number of DE genes : 70 (0 HSPs)

filtered <- filterData(dseq_orig, 
                        filtername = "annot", verbose = FALSE,
                        args=list(
                          signif = 10e-10, 
                          dbNames = c("swiss_prot", "ortho_db", "fly", "shrimp", "pfam")),
                        samples = c("BAT_E_2", "CAG_C_3", "CAG_E_1", "BIC_C_3"))
trackHSPGenes(filtered)
```

# Problem 2 : How many Ex90 genes have Annotations?
```{r}
# Total number of genes in EX90 : 17162
# With swiss_prot Annotations : 8751 (13 HSPs)
# With fly Annotations : 3820 (2 HSPs)
# With both swiss_prot and fly Annotations : 3734 (4 HSPs)

getGenesWithAnnot <- function(df_ex90, dbName){
  annotated_geneIds <- intersectAnnots(getCombinations(Inf), "gene_id", dbName)
  ex90_geneIds <- df_ex90$gene_id[df_ex90$gene_id %in% annotated_geneIds]
  df_ex90_geneIds <- df_geneIDs[df_geneIDs$gene_id %in% ex90_geneIds,]
  return(df_ex90_geneIds)
}

countHSP <- function(df_geneIDs, dbName="swiss_prot"){
  cnt <- getHSPGenes(geneids = df_geneIDs$gene_id, source = dbName) %>%
    nrow()
  return(cnt)
}

df_ex90 <- getDf_Ex90(CUTOFF = 90) %>% rename(acc = "gene_id")
df_ex90W_swissprot <- getGenesWithAnnot(df_ex90, "swiss_prot")
df_ex90W_fly <- getGenesWithAnnot(df_ex90, "fly")
df_ex90W_swissfly <- getGenesWithAnnot(df_ex90, c("swiss_prot", "fly"))

writeLines(paste0("Total number of genes in EX90 : ",nrow(df_ex90)))
writeLines(paste0("With swiss_prot Annotations : ", nrow(df_ex90W_swissprot)," (",countHSP(df_ex90W_swissprot)," HSPs)"))
writeLines(paste0("With fly Annotations : ", nrow(df_ex90W_fly)," (",countHSP(df_ex90W_fly, "fly")," HSPs)"))
writeLines(paste0("With both swiss_prot and fly Annotations : ", nrow(df_ex90W_swissfly)," (",countHSP(df_ex90W_swissfly, "swiss_prot")," HSPs)"))
```

# Problem 3 : DEG with all genes that have Swiss-prot annotation. 10^-10 and 10^-5 filters
```{r}
# SIGNIFICANCE                                             10e^-5              | 10e^-10
# Total number of genes                                  : 81278               | 59504
# After filtering, the number of 'HSP' genes is          : (251 HSPs)          | (153 HSPs)
# After fitting, number of outliers are                  : -361 (-1 HSPs)      | -316 (-1 HSPs)
# 
# Result of [ BAT.E ]          Removed by Ind. Filtering : -61168 (-198 HSPs)  | -0 (-0 HSPs)
#                              Final HSPs for testing    : (52 HSPs)           | (152 HSPs)
#                              Signif. DE genes          : 1268 (1 HSPs)       | 257 (0 HSPs)
# 
# Result of [ BIC.E ]          Removed by Ind. Filtering : -54263 (-178 HSPs)  | -38473 (-105 HSPs)
#                              Final HSPs for testing    : (72 HSPs)           | (47 HSPs)
#                              Signif. DE genes          : 97 (0 HSPs)         | 86 (0 HSPs)
# 
# Result of [ BAT.E-BIC.E ]    Removed by Ind. Filtering : -57016 (-191 HSPs)  | -41447 (-117 HSPs)
#                              Final HSPs for testing    : (59 HSPs)           | (35 HSPs)
#                              Signif. DE genes          : 193 (0 HSPs)        | 175 (0 HSPs)
# 
# Result of [ E ]              Removed by Ind. Filtering : -57016 (-191 HSPs)  | -41447 (-117 HSPs)
#                              Final HSPs for testing    : (59 HSPs)           | (35 HSPs)
#                              Signif. DE genes          : 235 (1 HSPs)        | 217 (1 HSPs)
# 
# Result of [ E+BAT.E ]        Removed by Ind. Filtering : -59768 (-196 HSPs)  | -40472 (-114 HSPs)
#                              Final HSPs for testing    : (54 HSPs)           | (38 HSPs)
#                              Signif. DE genes          : 3011 (4 HSPs)       | 2525 (3 HSPs)
# 
# Result of [ E+BIC.E ]        Removed by Ind. Filtering : -55643 (-185 HSPs)  | -39483 (-110 HSPs)
#                              Final HSPs for testing    : (65 HSPs)           | (42 HSPs)
#                              Signif. DE genes          : 307 (1 HSPs)        | 294 (0 HSPs)

filtered <- filterData(dseq_orig, 
                        samples = c("BAT_E_2", "CAG_C_3", "CAG_E_1", "BIC_C_3"),
                        filtername = "annot", verbose = FALSE,
                        args=list(
                          signif = 10e-10, 
                          dbNames = c("swiss_prot")))

# qcPrepare(filtered, "vst", plotMSD = TRUE) %>% plotPCA_Sample(c("location", "condition"))
counts(filtered@dseq) %>%  data.frame() %>% nrow()
trackHSPGenes(filtered)
```

# Problem 4 : DEG with all genes that have Fly annotation. 10^-10 and 10^-5 filters
```{r}
# SIGNIFICANCE                                             10e^-5              | 10e^-10  
# Total number of genes                                  : 17690               | 16740
# After filtering, the number of 'HSP' genes is          : 52 HSPs             | 52 HSPs
# After fitting, number of outliers are                  : -69 (-1 HSPs)       | -69 (-1 HSPs)
#   
# Result of [ BAT.E ]          Removed by Ind. Filtering : -10582 (-42 HSPs)   | -9999 (-42 HSPs)
#                              Final HSPs for testing    : (9 HSPs)            | (9 HSPs)
#                              Signif. DE genes          : 848 (1 HSPs)        | 833 (0 HSPs)
#   
# Result of [ BIC.E ]          Removed by Ind. Filtering : -8374 (-30 HSPs)    | -8520 (-33 HSPs)
#                              Final HSPs for testing    : (21 HSPs)           | (18 HSPs)
#                              Signif. DE genes          : 34 (0 HSPs)         | 32 (0 HSPs)
#   
# Result of [ BAT.E-BIC.E ]    Removed by Ind. Filtering : -11536 (-43 HSPs)   | -10297 (-42 HSPs)
#                              Final HSPs for testing    : (8 HSPs)            | (9 HSPs)
#                              Signif. DE genes          : 141 (0 HSPs)        | 133 (0 HSPs)
#   
# Result of [ E ]              Removed by Ind. Filtering : -9633 (-38 HSPs)    | -14549 (-44 HSPs)
#                              Final HSPs for testing    : (13 HSPs)           | (7 HSPs)
#                              Signif. DE genes          : 146 (0 HSPs)        | 167 (0 HSPs)
#
# Result of [ E+BAT.E ]        Removed by Ind. Filtering : -9633 (-38 HSPs)    |  -9398 (-41 HSPs)
#                              Final HSPs for testing    : (13 HSPs)           | (10 HSPs)
#                              Signif. DE genes          : 1770 (1 HSPs)       | 1711 (1 HSPs)
#
# Result of [ E+BIC.E ]        Removed by Ind. Filtering : -9012 (-32 HSPs)    | -7916 (-30 HSPs)
#                              Final HSPs for testing    : (19 HSPs)           | (21 HSPs)
#                              Signif. DE genes          : 142 (0 HSPs)        | 137 (0 HSPs)


filtered <- filterData(dseq_orig, 
                        samples = c("BAT_E_2", "CAG_C_3", "CAG_E_1", "BIC_C_3"),
                        filtername = "annot", verbose = FALSE,
                        args=list(
                          signif = 10e-05, 
                          dbNames = c("fly")))

# qcPrepare(filtered, "vst", plotMSD = TRUE) %>% plotPCA_Sample(c("location", "condition"))

trackHSPGenes(filtered, source = "fly")
```


